from .image_mask_random_selector import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

# 指定 JS 扩展所在的目录
WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
